name: study_aid
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.5.0-277.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.3.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter_drawing_board: ^0.7.0+2
  flutter_colorpicker: ^1.1.0
  stack_board: ^0.2.5
  flutter_quill: ^9.5.13
  screenshot: ^3.0.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 900
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Italic.ttf
          weight: 300