name: study_aid
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.5.0-277.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.3.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter_drawing_board: ^0.7.0+2
  flutter_colorpicker: ^1.1.0
  stack_board: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg  
  # fonts: