// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZr8mWwa19sqcMxm8KRoNezvaryH7j1A',
    appId: '1:544057525889:android:8b3abd20b77dd65bd72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e2fc5',
    storageBucket: 'study-aid-e2fc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs50h3J9qikwm2_eHneinBKXKkEa8x2wk',
    appId: '1:544057525889:ios:afd46761701a37cfd72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e2fc5',
    storageBucket: 'study-aid-e2fc5.appspot.com',
    androidClientId: '544057525889-ero5ibu14svjmt4dhmf2hfj8kkn7c9gn.apps.googleusercontent.com',
    iosClientId: '544057525889-2vp0hjeu926sj6vjruib03toob3a9v64.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs50h3J9qikwm2_eHneinBKXKkEa8x2wk',
    appId: '1:544057525889:ios:afd46761701a37cfd72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e2fc5',
    storageBucket: 'study-aid-e2fc5.appspot.com',
    androidClientId: '544057525889-ero5ibu14svjmt4dhmf2hfj8kkn7c9gn.apps.googleusercontent.com',
    iosClientId: '544057525889-2vp0hjeu926sj6vjruib03toob3a9v64.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAid',
  );

}