// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCADdqap2j18ObvCrdtSmEBags5Ga3lcyQ',
    appId: '1:494696942035:android:0f5d46b398abb710fbc726',
    messagingSenderId: '494696942035',
    projectId: 'study-aid-e3671',
    storageBucket: 'study-aid-e3671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eCxU0tyZr1qQGyPhDauZPitRaY3-IS4',
    appId: '1:494696942035:ios:620d0f8158fe00d2fbc726',
    messagingSenderId: '494696942035',
    projectId: 'study-aid-e3671',
    storageBucket: 'study-aid-e3671.firebasestorage.app',
    androidClientId: '494696942035-gl5f2h4ds3v2ujnbt19rl3vs1naffldh.apps.googleusercontent.com',
    iosClientId: '494696942035-t7af0qv756n0ljfj7td8rqnlbfs02jt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4eCxU0tyZr1qQGyPhDauZPitRaY3-IS4',
    appId: '1:494696942035:ios:620d0f8158fe00d2fbc726',
    messagingSenderId: '494696942035',
    projectId: 'study-aid-e3671',
    storageBucket: 'study-aid-e3671.firebasestorage.app',
    androidClientId: '494696942035-gl5f2h4ds3v2ujnbt19rl3vs1naffldh.apps.googleusercontent.com',
    iosClientId: '494696942035-t7af0qv756n0ljfj7td8rqnlbfs02jt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAid',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDp9nZj8ZCPs3xgoc-7VzdcZ83wKh4aa0A",
    authDomain: "study-aid-e3671.firebaseapp.com",
    projectId: "study-aid-e3671",
    storageBucket: "study-aid-e3671.firebasestorage.app",
    messagingSenderId: "494696942035",
    appId: "1:494696942035:web:82a6a45e0f4fc33efbc726",
    measurementId: "G-PQR70J890E"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHD-kUnZvGmwiLDu7UafNcIIrzxPbd5YY',
    appId: '1:544057525889:web:25a2a717ce7d9ad5d72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e3671',
    authDomain: 'study-aid-e3671.firebaseapp.com',
    storageBucket: 'study-aid-e3671.appspot.com',
    measurementId: 'G-6ECV4RGWEK',
  );

}