// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZr8mWwa19sqcMxm8KRoNezvaryH7j1A',
    appId: '1:544057525889:android:8b3abd20b77dd65bd72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e2fc5',
    storageBucket: 'study-aid-e2fc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs50h3J9qikwm2_eHneinBKXKkEa8x2wk',
    appId: '1:544057525889:ios:afd46761701a37cfd72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e2fc5',
    storageBucket: 'study-aid-e2fc5.appspot.com',
    androidClientId: '544057525889-7ectlugp0ioopiil0024ksv78e6m1fsk.apps.googleusercontent.com',
    iosClientId: '544057525889-2vp0hjeu926sj6vjruib03toob3a9v64.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs50h3J9qikwm2_eHneinBKXKkEa8x2wk',
    appId: '1:544057525889:ios:afd46761701a37cfd72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e2fc5',
    storageBucket: 'study-aid-e2fc5.appspot.com',
    androidClientId: '544057525889-7ectlugp0ioopiil0024ksv78e6m1fsk.apps.googleusercontent.com',
    iosClientId: '544057525889-2vp0hjeu926sj6vjruib03toob3a9v64.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAid',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDp9nZj8ZCPs3xgoc-7VzdcZ83wKh4aa0A",
    authDomain: "study-aid-e3671.firebaseapp.com",
    projectId: "study-aid-e3671",
    storageBucket: "study-aid-e3671.firebasestorage.app",
    messagingSenderId: "494696942035",
    appId: "1:494696942035:web:82a6a45e0f4fc33efbc726",
    measurementId: "G-PQR70J890E"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHD-kUnZvGmwiLDu7UafNcIIrzxPbd5YY',
    appId: '1:544057525889:web:25a2a717ce7d9ad5d72f80',
    messagingSenderId: '544057525889',
    projectId: 'study-aid-e2fc5',
    authDomain: 'study-aid-e2fc5.firebaseapp.com',
    storageBucket: 'study-aid-e2fc5.appspot.com',
    measurementId: 'G-6ECV4RGWEK',
  );

}