name: Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build android apk and appBundle
        run: flutter build apk

      - name: Build android ios
        run: flutter build ios --releasee --no-codesign
