name: Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Java 22
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: "temurin"
      #     java-version: "22"

      # - name: Clone Flutter repository with master channel
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: master

      # - name: Get Flutter Packages
      #   run: flutter pub get

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2

      # - name: Build android apk and appBundle
      #   run: flutter build apk
      - name: Navigate to ios directory
        run: cd ios

      - name: Update Podfile for iOS deployment target
        run: |
          echo "platform :ios, '13.0'" > Podfile.tmp
          if [ -f Podfile ]; then
            tail -n +2 Podfile >> Podfile.tmp
          fi
          mv Podfile.tmp Podfile

      # - name: Build android ios
      #   run: flutter build ipa --release --no-codesign
